//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.foundation.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowModeratedRooms" type="{}allowModeratedRooms"/>
 *         &lt;element name="floodControlResetTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="floodControlInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="floodControlMaxMessages" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="labels" type="{}labels"/>
 *         &lt;element name="maxroomusers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxdockitems" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="characterlimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="userroomcreate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="roomemptytimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxhistorymessages" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="showJoinLeaveMessages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gui" type="{}gui"/>
 *         &lt;element name="roomlist" type="{}roomlist"/>
 *         &lt;element name="getannouncementsinterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sendarchive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="banNotification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sendConnectionListInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="conferenceCallEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="conferenceCallText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userdatavalues" type="{}userdatavalues"/>
 *         &lt;element name="notextentry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="invisible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="adminrooms" type="{}adminrooms"/>
 *         &lt;element name="restrictedRooms" type="{}restrictedRooms"/>
 *         &lt;element name="initialroom" type="{}initialroom"/>
 *         &lt;element name="permitCopy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sessionTimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sessionTimeoutMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selecteduser" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="inactivityTimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="inactivityTimeoutMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="permitWhisper" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chat", propOrder = {
    "allowModeratedRooms",
    "floodControlResetTime",
    "floodControlInterval",
    "floodControlMaxMessages",
    "labels",
    "maxroomusers",
    "maxdockitems",
    "characterlimit",
    "userroomcreate",
    "roomemptytimeout",
    "maxhistorymessages",
    "showJoinLeaveMessages",
    "gui",
    "roomlist",
    "getannouncementsinterval",
    "sendarchive",
    "banNotification",
    "sendConnectionListInterval",
    "conferenceCallEnabled",
    "conferenceCallText",
    "userdatavalues",
    "notextentry",
    "invisible",
    "adminrooms",
    "restrictedRooms",
    "initialroom",
    "permitCopy",
    "sessionTimeout",
    "sessionTimeoutMessage",
    "selecteduser",
    "inactivityTimeout",
    "inactivityTimeoutMessage",
    "permitWhisper"
})
public class Chat {

    @XmlElement(required = true)
    protected AllowModeratedRooms allowModeratedRooms;
    protected int floodControlResetTime;
    protected int floodControlInterval;
    protected int floodControlMaxMessages;
    @XmlElement(required = true)
    protected Labels labels;
    protected int maxroomusers;
    protected int maxdockitems;
    protected int characterlimit;
    protected boolean userroomcreate;
    protected int roomemptytimeout;
    protected int maxhistorymessages;
    @XmlElement(required = true)
    protected String showJoinLeaveMessages;
    @XmlElement(required = true)
    protected Gui gui;
    @XmlElement(required = true)
    protected Roomlist roomlist;
    protected int getannouncementsinterval;
    protected boolean sendarchive;
    @XmlElement(required = true)
    protected String banNotification;
    protected int sendConnectionListInterval;
    protected boolean conferenceCallEnabled;
    @XmlElement(required = true)
    protected String conferenceCallText;
    @XmlElement(required = true)
    protected Userdatavalues userdatavalues;
    protected boolean notextentry;
    protected boolean invisible;
    @XmlElement(required = true)
    protected Adminrooms adminrooms;
    @XmlElement(required = true)
    protected RestrictedRooms restrictedRooms;
    @XmlElement(required = true)
    protected Initialroom initialroom;
    @XmlElement(required = true)
    protected String permitCopy;
    protected int sessionTimeout;
    @XmlElement(required = true)
    protected String sessionTimeoutMessage;
    protected int selecteduser;
    protected int inactivityTimeout;
    @XmlElement(required = true)
    protected String inactivityTimeoutMessage;
    protected boolean permitWhisper;

    /**
     * Gets the value of the allowModeratedRooms property.
     * 
     * @return
     *     possible object is
     *     {@link AllowModeratedRooms }
     *     
     */
    public AllowModeratedRooms getAllowModeratedRooms() {
        return allowModeratedRooms;
    }

    /**
     * Sets the value of the allowModeratedRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowModeratedRooms }
     *     
     */
    public void setAllowModeratedRooms(AllowModeratedRooms value) {
        this.allowModeratedRooms = value;
    }

    /**
     * Gets the value of the floodControlResetTime property.
     * 
     */
    public int getFloodControlResetTime() {
        return floodControlResetTime;
    }

    /**
     * Sets the value of the floodControlResetTime property.
     * 
     */
    public void setFloodControlResetTime(int value) {
        this.floodControlResetTime = value;
    }

    /**
     * Gets the value of the floodControlInterval property.
     * 
     */
    public int getFloodControlInterval() {
        return floodControlInterval;
    }

    /**
     * Sets the value of the floodControlInterval property.
     * 
     */
    public void setFloodControlInterval(int value) {
        this.floodControlInterval = value;
    }

    /**
     * Gets the value of the floodControlMaxMessages property.
     * 
     */
    public int getFloodControlMaxMessages() {
        return floodControlMaxMessages;
    }

    /**
     * Sets the value of the floodControlMaxMessages property.
     * 
     */
    public void setFloodControlMaxMessages(int value) {
        this.floodControlMaxMessages = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * @return
     *     possible object is
     *     {@link Labels }
     *     
     */
    public Labels getLabels() {
        return labels;
    }

    /**
     * Sets the value of the labels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labels }
     *     
     */
    public void setLabels(Labels value) {
        this.labels = value;
    }

    /**
     * Gets the value of the maxroomusers property.
     * 
     */
    public int getMaxroomusers() {
        return maxroomusers;
    }

    /**
     * Sets the value of the maxroomusers property.
     * 
     */
    public void setMaxroomusers(int value) {
        this.maxroomusers = value;
    }

    /**
     * Gets the value of the maxdockitems property.
     * 
     */
    public int getMaxdockitems() {
        return maxdockitems;
    }

    /**
     * Sets the value of the maxdockitems property.
     * 
     */
    public void setMaxdockitems(int value) {
        this.maxdockitems = value;
    }

    /**
     * Gets the value of the characterlimit property.
     * 
     */
    public int getCharacterlimit() {
        return characterlimit;
    }

    /**
     * Sets the value of the characterlimit property.
     * 
     */
    public void setCharacterlimit(int value) {
        this.characterlimit = value;
    }

    /**
     * Gets the value of the userroomcreate property.
     * 
     */
    public boolean isUserroomcreate() {
        return userroomcreate;
    }

    /**
     * Sets the value of the userroomcreate property.
     * 
     */
    public void setUserroomcreate(boolean value) {
        this.userroomcreate = value;
    }

    /**
     * Gets the value of the roomemptytimeout property.
     * 
     */
    public int getRoomemptytimeout() {
        return roomemptytimeout;
    }

    /**
     * Sets the value of the roomemptytimeout property.
     * 
     */
    public void setRoomemptytimeout(int value) {
        this.roomemptytimeout = value;
    }

    /**
     * Gets the value of the maxhistorymessages property.
     * 
     */
    public int getMaxhistorymessages() {
        return maxhistorymessages;
    }

    /**
     * Sets the value of the maxhistorymessages property.
     * 
     */
    public void setMaxhistorymessages(int value) {
        this.maxhistorymessages = value;
    }

    /**
     * Gets the value of the showJoinLeaveMessages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowJoinLeaveMessages() {
        return showJoinLeaveMessages;
    }

    /**
     * Sets the value of the showJoinLeaveMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowJoinLeaveMessages(String value) {
        this.showJoinLeaveMessages = value;
    }

    /**
     * Gets the value of the gui property.
     * 
     * @return
     *     possible object is
     *     {@link Gui }
     *     
     */
    public Gui getGui() {
        return gui;
    }

    /**
     * Sets the value of the gui property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gui }
     *     
     */
    public void setGui(Gui value) {
        this.gui = value;
    }

    /**
     * Gets the value of the roomlist property.
     * 
     * @return
     *     possible object is
     *     {@link Roomlist }
     *     
     */
    public Roomlist getRoomlist() {
        return roomlist;
    }

    /**
     * Sets the value of the roomlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Roomlist }
     *     
     */
    public void setRoomlist(Roomlist value) {
        this.roomlist = value;
    }

    /**
     * Gets the value of the getannouncementsinterval property.
     * 
     */
    public int getGetannouncementsinterval() {
        return getannouncementsinterval;
    }

    /**
     * Sets the value of the getannouncementsinterval property.
     * 
     */
    public void setGetannouncementsinterval(int value) {
        this.getannouncementsinterval = value;
    }

    /**
     * Gets the value of the sendarchive property.
     * 
     */
    public boolean isSendarchive() {
        return sendarchive;
    }

    /**
     * Sets the value of the sendarchive property.
     * 
     */
    public void setSendarchive(boolean value) {
        this.sendarchive = value;
    }

    /**
     * Gets the value of the banNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBanNotification() {
        return banNotification;
    }

    /**
     * Sets the value of the banNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBanNotification(String value) {
        this.banNotification = value;
    }

    /**
     * Gets the value of the sendConnectionListInterval property.
     * 
     */
    public int getSendConnectionListInterval() {
        return sendConnectionListInterval;
    }

    /**
     * Sets the value of the sendConnectionListInterval property.
     * 
     */
    public void setSendConnectionListInterval(int value) {
        this.sendConnectionListInterval = value;
    }

    /**
     * Gets the value of the conferenceCallEnabled property.
     * 
     */
    public boolean isConferenceCallEnabled() {
        return conferenceCallEnabled;
    }

    /**
     * Sets the value of the conferenceCallEnabled property.
     * 
     */
    public void setConferenceCallEnabled(boolean value) {
        this.conferenceCallEnabled = value;
    }

    /**
     * Gets the value of the conferenceCallText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConferenceCallText() {
        return conferenceCallText;
    }

    /**
     * Sets the value of the conferenceCallText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConferenceCallText(String value) {
        this.conferenceCallText = value;
    }

    /**
     * Gets the value of the userdatavalues property.
     * 
     * @return
     *     possible object is
     *     {@link Userdatavalues }
     *     
     */
    public Userdatavalues getUserdatavalues() {
        return userdatavalues;
    }

    /**
     * Sets the value of the userdatavalues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Userdatavalues }
     *     
     */
    public void setUserdatavalues(Userdatavalues value) {
        this.userdatavalues = value;
    }

    /**
     * Gets the value of the notextentry property.
     * 
     */
    public boolean isNotextentry() {
        return notextentry;
    }

    /**
     * Sets the value of the notextentry property.
     * 
     */
    public void setNotextentry(boolean value) {
        this.notextentry = value;
    }

    /**
     * Gets the value of the invisible property.
     * 
     */
    public boolean isInvisible() {
        return invisible;
    }

    /**
     * Sets the value of the invisible property.
     * 
     */
    public void setInvisible(boolean value) {
        this.invisible = value;
    }

    /**
     * Gets the value of the adminrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Adminrooms }
     *     
     */
    public Adminrooms getAdminrooms() {
        return adminrooms;
    }

    /**
     * Sets the value of the adminrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adminrooms }
     *     
     */
    public void setAdminrooms(Adminrooms value) {
        this.adminrooms = value;
    }

    /**
     * Gets the value of the restrictedRooms property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedRooms }
     *     
     */
    public RestrictedRooms getRestrictedRooms() {
        return restrictedRooms;
    }

    /**
     * Sets the value of the restrictedRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedRooms }
     *     
     */
    public void setRestrictedRooms(RestrictedRooms value) {
        this.restrictedRooms = value;
    }

    /**
     * Gets the value of the initialroom property.
     * 
     * @return
     *     possible object is
     *     {@link Initialroom }
     *     
     */
    public Initialroom getInitialroom() {
        return initialroom;
    }

    /**
     * Sets the value of the initialroom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initialroom }
     *     
     */
    public void setInitialroom(Initialroom value) {
        this.initialroom = value;
    }

    /**
     * Gets the value of the permitCopy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermitCopy() {
        return permitCopy;
    }

    /**
     * Sets the value of the permitCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermitCopy(String value) {
        this.permitCopy = value;
    }

    /**
     * Gets the value of the sessionTimeout property.
     * 
     */
    public int getSessionTimeout() {
        return sessionTimeout;
    }

    /**
     * Sets the value of the sessionTimeout property.
     * 
     */
    public void setSessionTimeout(int value) {
        this.sessionTimeout = value;
    }

    /**
     * Gets the value of the sessionTimeoutMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionTimeoutMessage() {
        return sessionTimeoutMessage;
    }

    /**
     * Sets the value of the sessionTimeoutMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionTimeoutMessage(String value) {
        this.sessionTimeoutMessage = value;
    }

    /**
     * Gets the value of the selecteduser property.
     * 
     */
    public int getSelecteduser() {
        return selecteduser;
    }

    /**
     * Sets the value of the selecteduser property.
     * 
     */
    public void setSelecteduser(int value) {
        this.selecteduser = value;
    }

    /**
     * Gets the value of the inactivityTimeout property.
     * 
     */
    public int getInactivityTimeout() {
        return inactivityTimeout;
    }

    /**
     * Sets the value of the inactivityTimeout property.
     * 
     */
    public void setInactivityTimeout(int value) {
        this.inactivityTimeout = value;
    }

    /**
     * Gets the value of the inactivityTimeoutMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInactivityTimeoutMessage() {
        return inactivityTimeoutMessage;
    }

    /**
     * Sets the value of the inactivityTimeoutMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInactivityTimeoutMessage(String value) {
        this.inactivityTimeoutMessage = value;
    }

    /**
     * Gets the value of the permitWhisper property.
     * 
     */
    public boolean isPermitWhisper() {
        return permitWhisper;
    }

    /**
     * Sets the value of the permitWhisper property.
     * 
     */
    public void setPermitWhisper(boolean value) {
        this.permitWhisper = value;
    }

}
