//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.foundation.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domain complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domain">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maxxmlretries" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="avenabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="forbiddenwordslist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allowCalls" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domainPrefReloadInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxUsers" type="{}maxUsers"/>
 *         &lt;element name="domainInvalid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="adminsRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="textColors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="smileys" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chat" type="{}chat"/>
 *       &lt;/sequence>
 *       &lt;attribute name="includeAdmins" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domain", propOrder = {
    "maxxmlretries",
    "avenabled",
    "forbiddenwordslist",
    "allowCalls",
    "domainPrefReloadInterval",
    "maxUsers",
    "domainInvalid",
    "adminsRequired",
    "textColors",
    "smileys",
    "chat"
})
public class Domain {

    protected int maxxmlretries;
    protected boolean avenabled;
    @XmlElement(required = true)
    protected String forbiddenwordslist;
    @XmlElement(required = true)
    protected String allowCalls;
    protected int domainPrefReloadInterval;
    @XmlElement(required = true)
    protected MaxUsers maxUsers;
    protected boolean domainInvalid;
    protected boolean adminsRequired;
    @XmlElement(required = true)
    protected String textColors;
    @XmlElement(required = true)
    protected String smileys;
    @XmlElement(required = true)
    protected Chat chat;
    @XmlAttribute
    protected Boolean includeAdmins;

    /**
     * Gets the value of the maxxmlretries property.
     * 
     */
    public int getMaxxmlretries() {
        return maxxmlretries;
    }

    /**
     * Sets the value of the maxxmlretries property.
     * 
     */
    public void setMaxxmlretries(int value) {
        this.maxxmlretries = value;
    }

    /**
     * Gets the value of the avenabled property.
     * 
     */
    public boolean isAvenabled() {
        return avenabled;
    }

    /**
     * Sets the value of the avenabled property.
     * 
     */
    public void setAvenabled(boolean value) {
        this.avenabled = value;
    }

    /**
     * Gets the value of the forbiddenwordslist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForbiddenwordslist() {
        return forbiddenwordslist;
    }

    /**
     * Sets the value of the forbiddenwordslist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForbiddenwordslist(String value) {
        this.forbiddenwordslist = value;
    }

    /**
     * Gets the value of the allowCalls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowCalls() {
        return allowCalls;
    }

    /**
     * Sets the value of the allowCalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowCalls(String value) {
        this.allowCalls = value;
    }

    /**
     * Gets the value of the domainPrefReloadInterval property.
     * 
     */
    public int getDomainPrefReloadInterval() {
        return domainPrefReloadInterval;
    }

    /**
     * Sets the value of the domainPrefReloadInterval property.
     * 
     */
    public void setDomainPrefReloadInterval(int value) {
        this.domainPrefReloadInterval = value;
    }

    /**
     * Gets the value of the maxUsers property.
     * 
     * @return
     *     possible object is
     *     {@link MaxUsers }
     *     
     */
    public MaxUsers getMaxUsers() {
        return maxUsers;
    }

    /**
     * Sets the value of the maxUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxUsers }
     *     
     */
    public void setMaxUsers(MaxUsers value) {
        this.maxUsers = value;
    }

    /**
     * Gets the value of the domainInvalid property.
     * 
     */
    public boolean isDomainInvalid() {
        return domainInvalid;
    }

    /**
     * Sets the value of the domainInvalid property.
     * 
     */
    public void setDomainInvalid(boolean value) {
        this.domainInvalid = value;
    }

    /**
     * Gets the value of the adminsRequired property.
     * 
     */
    public boolean isAdminsRequired() {
        return adminsRequired;
    }

    /**
     * Sets the value of the adminsRequired property.
     * 
     */
    public void setAdminsRequired(boolean value) {
        this.adminsRequired = value;
    }

    /**
     * Gets the value of the textColors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColors() {
        return textColors;
    }

    /**
     * Sets the value of the textColors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColors(String value) {
        this.textColors = value;
    }

    /**
     * Gets the value of the smileys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmileys() {
        return smileys;
    }

    /**
     * Sets the value of the smileys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmileys(String value) {
        this.smileys = value;
    }

    /**
     * Gets the value of the chat property.
     * 
     * @return
     *     possible object is
     *     {@link Chat }
     *     
     */
    public Chat getChat() {
        return chat;
    }

    /**
     * Sets the value of the chat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chat }
     *     
     */
    public void setChat(Chat value) {
        this.chat = value;
    }

    /**
     * Gets the value of the includeAdmins property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeAdmins() {
        return includeAdmins;
    }

    /**
     * Sets the value of the includeAdmins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeAdmins(Boolean value) {
        this.includeAdmins = value;
    }

}
