//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.foundation.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gui complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gui">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="viewprofile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="instantcommunicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="addfriend" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="reportabuse" type="{}reportabuse"/>
 *         &lt;element name="titleBarColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scrollTrackColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outerBackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="innerBackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uiFontColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buttonColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leftPaneMinimized" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dockMinimized" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="images" type="{}images"/>
 *         &lt;element name="initialinputlines" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="help" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="modulelist" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="search" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gui", propOrder = {
    "viewprofile",
    "instantcommunicator",
    "addfriend",
    "block",
    "reportabuse",
    "titleBarColor",
    "scrollTrackColor",
    "outerBackgroundColor",
    "innerBackgroundColor",
    "uiFontColor",
    "buttonColor",
    "leftPaneMinimized",
    "dockMinimized",
    "images",
    "initialinputlines",
    "help",
    "modulelist",
    "search"
})
public class Gui {

    protected boolean viewprofile;
    protected boolean instantcommunicator;
    protected Boolean addfriend;
    protected boolean block;
    @XmlElement(required = true)
    protected Reportabuse reportabuse;
    @XmlElement(required = true)
    protected String titleBarColor;
    @XmlElement(required = true)
    protected String scrollTrackColor;
    @XmlElement(required = true)
    protected String outerBackgroundColor;
    @XmlElement(required = true)
    protected String innerBackgroundColor;
    @XmlElement(required = true)
    protected String uiFontColor;
    @XmlElement(required = true)
    protected String buttonColor;
    protected boolean leftPaneMinimized;
    protected boolean dockMinimized;
    @XmlElement(required = true)
    protected Images images;
    protected int initialinputlines;
    protected boolean help;
    protected String modulelist;
    protected String search;

    /**
     * Gets the value of the viewprofile property.
     * 
     */
    public boolean isViewprofile() {
        return viewprofile;
    }

    /**
     * Sets the value of the viewprofile property.
     * 
     */
    public void setViewprofile(boolean value) {
        this.viewprofile = value;
    }

    /**
     * Gets the value of the instantcommunicator property.
     * 
     */
    public boolean isInstantcommunicator() {
        return instantcommunicator;
    }

    /**
     * Sets the value of the instantcommunicator property.
     * 
     */
    public void setInstantcommunicator(boolean value) {
        this.instantcommunicator = value;
    }

    /**
     * Gets the value of the addfriend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddfriend() {
        return addfriend;
    }

    /**
     * Sets the value of the addfriend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddfriend(Boolean value) {
        this.addfriend = value;
    }

    /**
     * Gets the value of the block property.
     * 
     */
    public boolean isBlock() {
        return block;
    }

    /**
     * Sets the value of the block property.
     * 
     */
    public void setBlock(boolean value) {
        this.block = value;
    }

    /**
     * Gets the value of the reportabuse property.
     * 
     * @return
     *     possible object is
     *     {@link Reportabuse }
     *     
     */
    public Reportabuse getReportabuse() {
        return reportabuse;
    }

    /**
     * Sets the value of the reportabuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reportabuse }
     *     
     */
    public void setReportabuse(Reportabuse value) {
        this.reportabuse = value;
    }

    /**
     * Gets the value of the titleBarColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleBarColor() {
        return titleBarColor;
    }

    /**
     * Sets the value of the titleBarColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleBarColor(String value) {
        this.titleBarColor = value;
    }

    /**
     * Gets the value of the scrollTrackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrollTrackColor() {
        return scrollTrackColor;
    }

    /**
     * Sets the value of the scrollTrackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrollTrackColor(String value) {
        this.scrollTrackColor = value;
    }

    /**
     * Gets the value of the outerBackgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOuterBackgroundColor() {
        return outerBackgroundColor;
    }

    /**
     * Sets the value of the outerBackgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOuterBackgroundColor(String value) {
        this.outerBackgroundColor = value;
    }

    /**
     * Gets the value of the innerBackgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInnerBackgroundColor() {
        return innerBackgroundColor;
    }

    /**
     * Sets the value of the innerBackgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInnerBackgroundColor(String value) {
        this.innerBackgroundColor = value;
    }

    /**
     * Gets the value of the uiFontColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiFontColor() {
        return uiFontColor;
    }

    /**
     * Sets the value of the uiFontColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiFontColor(String value) {
        this.uiFontColor = value;
    }

    /**
     * Gets the value of the buttonColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getButtonColor() {
        return buttonColor;
    }

    /**
     * Sets the value of the buttonColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setButtonColor(String value) {
        this.buttonColor = value;
    }

    /**
     * Gets the value of the leftPaneMinimized property.
     * 
     */
    public boolean isLeftPaneMinimized() {
        return leftPaneMinimized;
    }

    /**
     * Sets the value of the leftPaneMinimized property.
     * 
     */
    public void setLeftPaneMinimized(boolean value) {
        this.leftPaneMinimized = value;
    }

    /**
     * Gets the value of the dockMinimized property.
     * 
     */
    public boolean isDockMinimized() {
        return dockMinimized;
    }

    /**
     * Sets the value of the dockMinimized property.
     * 
     */
    public void setDockMinimized(boolean value) {
        this.dockMinimized = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link Images }
     *     
     */
    public Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link Images }
     *     
     */
    public void setImages(Images value) {
        this.images = value;
    }

    /**
     * Gets the value of the initialinputlines property.
     * 
     */
    public int getInitialinputlines() {
        return initialinputlines;
    }

    /**
     * Sets the value of the initialinputlines property.
     * 
     */
    public void setInitialinputlines(int value) {
        this.initialinputlines = value;
    }

    /**
     * Gets the value of the help property.
     * 
     */
    public boolean isHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     */
    public void setHelp(boolean value) {
        this.help = value;
    }

    /**
     * Gets the value of the modulelist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModulelist() {
        return modulelist;
    }

    /**
     * Sets the value of the modulelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModulelist(String value) {
        this.modulelist = value;
    }

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearch(String value) {
        this.search = value;
    }

}
