//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.foundation.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for reportabuse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reportabuse">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="textLines" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="avEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="avWebAccessible" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="avSeconds" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="avUserID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportabuse", propOrder = {
    "value"
})
public class Reportabuse {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected Integer textLines;
    @XmlAttribute
    protected Boolean avEnabled;
    @XmlAttribute
    protected Boolean avWebAccessible;
    @XmlAttribute
    protected Integer avSeconds;
    @XmlAttribute
    protected String avUserID;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the textLines property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTextLines() {
        return textLines;
    }

    /**
     * Sets the value of the textLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextLines(Integer value) {
        this.textLines = value;
    }

    /**
     * Gets the value of the avEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvEnabled() {
        return avEnabled;
    }

    /**
     * Sets the value of the avEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvEnabled(Boolean value) {
        this.avEnabled = value;
    }

    /**
     * Gets the value of the avWebAccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvWebAccessible() {
        return avWebAccessible;
    }

    /**
     * Sets the value of the avWebAccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvWebAccessible(Boolean value) {
        this.avWebAccessible = value;
    }

    /**
     * Gets the value of the avSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAvSeconds() {
        return avSeconds;
    }

    /**
     * Sets the value of the avSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAvSeconds(Integer value) {
        this.avSeconds = value;
    }

    /**
     * Gets the value of the avUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvUserID() {
        return avUserID;
    }

    /**
     * Sets the value of the avUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvUserID(String value) {
        this.avUserID = value;
    }

}
