//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.foundation.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userlist complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userlist">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gui" type="{}gui"/>
 *         &lt;element name="buddyviewableonly" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userlist", propOrder = {
    "gui",
    "buddyviewableonly"
})
public class Userlist {

    @XmlElement(required = true)
    protected Gui gui;
    @XmlElement(required = true)
    protected String buddyviewableonly;

    /**
     * Gets the value of the gui property.
     * 
     * @return
     *     possible object is
     *     {@link Gui }
     *     
     */
    public Gui getGui() {
        return gui;
    }

    /**
     * Sets the value of the gui property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gui }
     *     
     */
    public void setGui(Gui value) {
        this.gui = value;
    }

    /**
     * Gets the value of the buddyviewableonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuddyviewableonly() {
        return buddyviewableonly;
    }

    /**
     * Sets the value of the buddyviewableonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuddyviewableonly(String value) {
        this.buddyviewableonly = value;
    }

}
