//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for labels complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="labels">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userdata" type="{}userdata"/>
 *         &lt;element name="lobby" type="{}lobby"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "labels", propOrder = {
    "userdata",
    "lobby"
})
public class Labels {

    @XmlElement(required = true)
    protected Userdata userdata;
    @XmlElement(required = true)
    protected Lobby lobby;

    /**
     * Gets the value of the userdata property.
     * 
     * @return
     *     possible object is
     *     {@link Userdata }
     *     
     */
    public Userdata getUserdata() {
        return userdata;
    }

    /**
     * Sets the value of the userdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Userdata }
     *     
     */
    public void setUserdata(Userdata value) {
        this.userdata = value;
    }

    /**
     * Gets the value of the lobby property.
     * 
     * @return
     *     possible object is
     *     {@link Lobby }
     *     
     */
    public Lobby getLobby() {
        return lobby;
    }

    /**
     * Sets the value of the lobby property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lobby }
     *     
     */
    public void setLobby(Lobby value) {
        this.lobby = value;
    }

}
