//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for minichat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="minichat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="useAnonymousScreenNames" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="showUserCount" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="showWatcherUserCount" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowTextInput" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowRoomUserlist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "minichat", propOrder = {
    "useAnonymousScreenNames",
    "showUserCount",
    "showWatcherUserCount",
    "allowTextInput",
    "allowRoomUserlist"
})
public class Minichat {

    protected boolean useAnonymousScreenNames;
    protected boolean showUserCount;
    protected boolean showWatcherUserCount;
    protected boolean allowTextInput;
    protected boolean allowRoomUserlist;

    /**
     * Gets the value of the useAnonymousScreenNames property.
     * 
     */
    public boolean isUseAnonymousScreenNames() {
        return useAnonymousScreenNames;
    }

    /**
     * Sets the value of the useAnonymousScreenNames property.
     * 
     */
    public void setUseAnonymousScreenNames(boolean value) {
        this.useAnonymousScreenNames = value;
    }

    /**
     * Gets the value of the showUserCount property.
     * 
     */
    public boolean isShowUserCount() {
        return showUserCount;
    }

    /**
     * Sets the value of the showUserCount property.
     * 
     */
    public void setShowUserCount(boolean value) {
        this.showUserCount = value;
    }

    /**
     * Gets the value of the showWatcherUserCount property.
     * 
     */
    public boolean isShowWatcherUserCount() {
        return showWatcherUserCount;
    }

    /**
     * Sets the value of the showWatcherUserCount property.
     * 
     */
    public void setShowWatcherUserCount(boolean value) {
        this.showWatcherUserCount = value;
    }

    /**
     * Gets the value of the allowTextInput property.
     * 
     */
    public boolean isAllowTextInput() {
        return allowTextInput;
    }

    /**
     * Sets the value of the allowTextInput property.
     * 
     */
    public void setAllowTextInput(boolean value) {
        this.allowTextInput = value;
    }

    /**
     * Gets the value of the allowRoomUserlist property.
     * 
     */
    public boolean isAllowRoomUserlist() {
        return allowRoomUserlist;
    }

    /**
     * Sets the value of the allowRoomUserlist property.
     * 
     */
    public void setAllowRoomUserlist(boolean value) {
        this.allowRoomUserlist = value;
    }

}
