//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.28 at 03:34:04 PM PST 
//


package com.blackbox.userplane;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="speaker" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="displayname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avsettings" type="{}avsettings" minOccurs="0"/>
 *         &lt;element name="buddylist" type="{}buddylist" minOccurs="0"/>
 *         &lt;element name="blocklist" type="{}blocklist" minOccurs="0"/>
 *         &lt;element name="images" type="{}images"/>
 *         &lt;element name="chat" type="{}chat" minOccurs="0"/>
 *         &lt;element name="userlist" type="{}userlist" minOccurs="0"/>
 *         &lt;element name="minichat" type="{}minichat" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {
    "userid",
    "admin",
    "speaker",
    "displayname",
    "avsettings",
    "buddylist",
    "blocklist",
    "images",
    "chat",
    "userlist",
    "minichat"
})
public class User {

    @XmlElement(required = true)
    protected String userid;
    protected Boolean admin;
    protected Boolean speaker;
    @XmlElement(required = true)
    protected String displayname;
    protected Avsettings avsettings;
    protected Buddylist buddylist;
    protected Blocklist blocklist;
    @XmlElement(required = true)
    protected Images images;
    protected Chat chat;
    protected Userlist userlist;
    protected Minichat minichat;

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserid(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the admin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdmin() {
        return admin;
    }

    /**
     * Sets the value of the admin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdmin(Boolean value) {
        this.admin = value;
    }

    /**
     * Gets the value of the speaker property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSpeaker() {
        return speaker;
    }

    /**
     * Sets the value of the speaker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSpeaker(Boolean value) {
        this.speaker = value;
    }

    /**
     * Gets the value of the displayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * Sets the value of the displayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayname(String value) {
        this.displayname = value;
    }

    /**
     * Gets the value of the avsettings property.
     * 
     * @return
     *     possible object is
     *     {@link Avsettings }
     *     
     */
    public Avsettings getAvsettings() {
        return avsettings;
    }

    /**
     * Sets the value of the avsettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Avsettings }
     *     
     */
    public void setAvsettings(Avsettings value) {
        this.avsettings = value;
    }

    /**
     * Gets the value of the buddylist property.
     * 
     * @return
     *     possible object is
     *     {@link Buddylist }
     *     
     */
    public Buddylist getBuddylist() {
        return buddylist;
    }

    /**
     * Sets the value of the buddylist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Buddylist }
     *     
     */
    public void setBuddylist(Buddylist value) {
        this.buddylist = value;
    }

    /**
     * Gets the value of the blocklist property.
     * 
     * @return
     *     possible object is
     *     {@link Blocklist }
     *     
     */
    public Blocklist getBlocklist() {
        return blocklist;
    }

    /**
     * Sets the value of the blocklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blocklist }
     *     
     */
    public void setBlocklist(Blocklist value) {
        this.blocklist = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link Images }
     *     
     */
    public Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link Images }
     *     
     */
    public void setImages(Images value) {
        this.images = value;
    }

    /**
     * Gets the value of the chat property.
     * 
     * @return
     *     possible object is
     *     {@link Chat }
     *     
     */
    public Chat getChat() {
        return chat;
    }

    /**
     * Sets the value of the chat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chat }
     *     
     */
    public void setChat(Chat value) {
        this.chat = value;
    }

    /**
     * Gets the value of the userlist property.
     * 
     * @return
     *     possible object is
     *     {@link Userlist }
     *     
     */
    public Userlist getUserlist() {
        return userlist;
    }

    /**
     * Sets the value of the userlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Userlist }
     *     
     */
    public void setUserlist(Userlist value) {
        this.userlist = value;
    }

    /**
     * Gets the value of the minichat property.
     * 
     * @return
     *     possible object is
     *     {@link Minichat }
     *     
     */
    public Minichat getMinichat() {
        return minichat;
    }

    /**
     * Sets the value of the minichat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Minichat }
     *     
     */
    public void setMinichat(Minichat value) {
        this.minichat = value;
    }

}
