begin;
delete from bb_billing_info where user_guid in (select guid from bb_user where username is null and email is null);
delete from bb_billing_info where user_guid in (select guid from bb_user where password is null);
delete from bb_profile where user_guid in (select guid from bb_user where username is null and email is null);
delete from bb_user where username is null and email is null;
delete from bb_user where password is null;
create sequence fix_email;
update bb_user set email = nextval('fix_email') where email is  null;
drop sequence fix_email;
alter table bb_user alter column email set not null;
alter table bb_user alter column username set not null;
alter table bb_user alter column password set not null;
commit;begin;
delete from bb_billing_info where user_guid in (select guid from bb_user where username is null and email is null);
delete from bb_billing_info where user_guid in (select guid from bb_user where password is null);
delete from bb_profile where user_guid in (select guid from bb_user where username is null and email is null);
delete from bb_user where username is null and email is null;
delete from bb_user where password is null;
create sequence fix_email;
update bb_user set email = nextval('fix_email') where email is  null;
drop sequence fix_email;
alter table bb_user alter column email set not null;
alter table bb_user alter column username set not null;
alter table bb_user alter column password set not null;
commit;
